spring:
  output:
      ansi:
        enabled: ALWAYS
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password:
    platform: h2
    initialize: true
    url: jdbc:h2:~/file/InVaderDb;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true

invader:
  agent:
    delayMin: 0
    delayMax: 2000
    failure: 0.5